- name: Destroying Kubernetes Cluster
  hosts: k8s-nodes
  gather_facts: true
  become: yes
  become_method: su
  become_user: root
  environment:
    PATH: "/usr/java/default/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/sbin"
  roles:
     - role: reset-k8s-cluster

- name: Stop kubelet service
  hosts: k8s-nodes
  gather_facts: true
  become: yes
  become_method: su
  become_user: root
  tasks:
    - name: Stop service httpd, if started
      service:
        name: kubelet
        state: stopped
      failed_when: false

