---
     - name: Create a login user
       user:
         name: "{{ user_name }}"
         password: "{{ password | password_hash('sha512') }}"
         groups: # Empty by default, here we give it some groups
          - "{{ group_name }}"
         state: present
         shell: /bin/bash       # Defaults to /bin/bash
         system: no             # Defaults to no
         createhome: yes        # Defaults to yes
         home: "{{ user_home }}"  # Defaults to /home/<username>
