---
  - name: Joining HA master nodes
    environment:
      PATH: "/usr/java/default/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/sbin"
    shell: "{{ join_cluster }}  --experimental-control-plane --certificate-key {{ cluster_certs }}"
    register: out
  - debug: msg={{ out.stdout }}

  - name: Changing file permissions
    file:
      path: /etc/kubernetes/admin.conf
      state: file
      mode: u=rw,g=-,o=r

  - name: Creating .kube directory
    become: yes
    become_user: "{{ default_ssh_user }}"  
    file:
      path: $HOME/.kube
      state: directory
      mode: 0755
 
  - name: Copying admin.conf to user's kube config
    become: yes
    become_user: "{{ default_ssh_user }}"  
    copy:
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      remote_src: yes
      owner: "{{ default_ssh_user }}"

  - name: Changing file permissions
    become: yes
    become_user: "{{ default_ssh_user }}"
    file:
      path: $HOME/.kube/config
      state: file
      mode: u=rw,g=-,o=-

  - name: Changing file permissions
    file:
      path: /etc/kubernetes/admin.conf
      state: file
      mode: u=rw,g=-,o=-
